server:
  port: 8090

spring:
  application:
    name: auth-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    stream:
      username: guest
      password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

firebase:
  credentials:
    path: ${GOOGLE_APPLICATION_CREDENTIALS:../secrets/firebase-user.json}

jwt:
  secret: ${JWT_SECRET:defaultFallbackSecretKey1234567890}

app:
  rabbitmq:
    exchange: main_exchange
    # Queue và routing key riêng cho từng service
    user:
      queue: user_queue
      routing_key: user_routing_key
