server:
  port: 8090

spring:
  application:
    name: auth-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    dynamic: true
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5      # retry tối đa 5 lần
          initial-interval: 2000   # 2s
          multiplier: 2.0
          max-interval: 10000
        default-requeue-rejected: false
  data:
    redis:
      host: redis
      port: 6379
      connect-timeout: 6000
      timeout: 2000
      password: ${REDIS_PASSWORD:defaultPassword}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

firebase:
  credentials:
    path: ${GOOGLE_APPLICATION_CREDENTIALS:../secrets/firebase-user.json}

jwt:
  secret: ${JWT_SECRET:defaultFallbackSecretKey1234567890}

app:
  rabbitmq:
    exchange: main_exchange
    # Queue và routing key riêng cho từng service
    user:
      queue: user_queue
      routing_key: user_routing_key
    # For Forgot password function
    forgot-password:
      queue: forgot_pass_queue
      routing_key: forgot_pass_routing_key