server:
  port: 8090

spring:
  application:
    name: auth-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    stream:
      username: guest
      password: guest
  data:
    redis:
      host: redis
      port: 6379
      connect-timeout: 6000
      timeout: 2000
      password: ${REDIS_PASSWORD:defaultPassword}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

firebase:
  credentials:
    path: ${GOOGLE_APPLICATION_CREDENTIALS:../secrets/firebase-hmk-database.json}

jwt:
  secret: ${JWT_SECRET:defaultFallbackSecretKey1234567890}

app:
  rabbitmq:
    exchange: main_exchange
    # Queue và routing key riêng cho từng service
    user:
      queue: user_queue
      routing_key: user_routing_key
    # For Forgot password function
    forgot-password:
      queue: forgot_pass_queue
      routing_key: forgot_pass_routing_key