server:
  port: 8092

spring:
  application:
    name: notification-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    dynamic: true
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5      # retry tối đa 5 lần
          initial-interval: 2000   # 2s
          multiplier: 2.0
          max-interval: 10000
        default-requeue-rejected: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_APP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  rabbitmq:
    exchange: main_exchange
    # For order mail sender
    order-mail:
      queue: order_mail_queue
      routing-key: order_mail_routing_key

    # For Forgot password function
    forgot-password:
      queue: forgot_pass_queue
      routing_key: forgot_pass_routing_key

  mail:
    from: ${MAIL_USERNAME}




