networks:
  backend:
    driver: bridge

volumes:
  esdata:
  redisdata:
  rabbitmqdata:


services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks: [ backend ]
    environment:
      - JWT_SECRET=${JWT_SECRET}

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks: [ backend ]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --appendonly yes

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks: [ backend ]
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8090:8090"
    networks: [ backend ]
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-user.json
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    volumes:
      - ./secrets/firebase-user.json:/app/firebase-user.json

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks: [ backend ]

  blog-service:
    build:
      context: ./blog-service
      dockerfile: Dockerfile
    container_name: blog-service
    ports:
      - "8084:8084"
    networks: [ backend ]
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-blog.json
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    volumes:
      - ./secrets/firebase-blog.json:/app/firebase-blog.json
    depends_on:
      rabbitmq:
        condition: service_started

  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    container_name: cart-service
    ports:
      - "8083:8083"
    networks: [ backend ]
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-cart.json
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    volumes:
      - ./secrets/firebase-cart.json:/app/firebase-cart.json

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8082:8082"
    networks: [ backend ]
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-order.json
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    volumes:
      - ./secrets/firebase-order.json:/app/firebase-order.json

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8081:8081"
    networks: [ backend ]
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-product.json
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    volumes:
      - ./secrets/firebase-product.json:/app/firebase-product.json
      - esdata:/usr/share/elasticsearch/data
    depends_on:
      elasticsearch:
        condition: service_healthy

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8085:8085"
    networks: [ backend ]
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-user.json
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    volumes:
      - ./secrets/firebase-user.json:/app/firebase-user.json

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "8089:8089"
    networks: [ backend ]
    environment:
      - VNP_URL=${VNP_URL}
      - VNP_TMN_CODE=${VNP_TMN_CODE}
      - VNP_SECRET_KEY=${VNP_SECRET_KEY}
      - VNP_RETURN_URL=${VNP_RETURN_URL}
      - VNP_VERSION=${VNP_VERSION}
      - VNP_COMMAND=${VNP_COMMAND}
      - VNP_ORDER_TYPE=${VNP_ORDER_TYPE}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
  file-service:
    build:
      context: ./file-service
      dockerfile: Dockerfile
    container_name: file-service
    ports:
      - "8091:8091"
    networks: [ backend ]
    environment:
      - SUPABASE_SECRETS_PATH=/app/supabase-secrets.json
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    volumes:
      - ./secrets/supabase-secrets.json:/app/supabase-secrets.json

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "8092:8092"
    networks: [ backend ]
    environment:
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_APP_PASSWORD=${MAIL_APP_PASSWORD}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    env_file:
      - .env
