services:
  service-registry:
    build:
      context: ./service_registry
      dockerfile: Dockerfile
    container_name: service-registry
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      service-registry:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - JWT_SECRET=${JWT_SECRET}

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8090:8090"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-user.json
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    volumes:
      - ./secrets/firebase-user.json:/app/firebase-user.json
    depends_on:
      service-registry:
        condition: service_healthy

  blog-service:
    build:
      context: ./blog-service
      dockerfile: Dockerfile
    container_name: blog-service
    ports:
      - "8084:8084"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-blog.json
    volumes:
      - ./secrets/firebase-blog.json:/app/firebase-blog.json
    depends_on:
      service-registry:
        condition: service_healthy

  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    container_name: cart-service
    ports:
      - "8083:8083"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-cart.json
    volumes:
      - ./secrets/firebase-cart.json:/app/firebase-cart.json
    depends_on:
      service-registry:
        condition: service_healthy

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-order.json
    volumes:
      - ./secrets/firebase-order.json:/app/firebase-order.json
    depends_on:
      service-registry:
        condition: service_healthy

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8081:8081"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-product.json
      - ALGOLIA_APP_ID=${ALGOLIA_APP_ID}
      - ALGOLIA_API_KEY=${ALGOLIA_API_KEY}
      - ALGOLIA_API_WRITE_KEY=${ALGOLIA_API_WRITE_KEY}
    volumes:
      - ./secrets/firebase-product.json:/app/firebase-product.json
    depends_on:
      service-registry:
        condition: service_healthy

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8085:8085"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-user.json
    volumes:
      - ./secrets/firebase-user.json:/app/firebase-user.json
    depends_on:
      service-registry:
        condition: service_healthy

  store-service:
    build:
      context: ./store-service
      dockerfile: Dockerfile
    container_name: store-service
    ports:
      - "8087:8087"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-store.json
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_APPLICATION_NAME=store-service
      - SERVER_PORT=8087
    volumes:
      - ./secrets/firebase-store.json:/app/firebase-store.json
    depends_on:
      service-registry:
        condition: service_healthy

  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    container_name: inventory-service
    ports:
      - "8088:8088"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-inventory.json
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_APPLICATION_NAME=inventory-service
      - SERVER_PORT=8088
    volumes:
      - ./secrets/firebase-inventory.json:/app/firebase-inventory.json
    depends_on:
      service-registry:
        condition: service_healthy
