server:
  port: 8084

spring:
  application:
    name: blog-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    stream:
      username: ${RABBITMQ_USER}
      password: ${RABBITMQ_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

firebase:
  credentials:
    path: ${GOOGLE_APPLICATION_CREDENTIALS:../secrets/firebase-blog.json}

app:
  rabbitmq:
    exchange: main_exchange
    # Queue và routing key riêng cho từng service
    blog:
      queue: blog_queue
      routing-key: blog_routing_key
    banner:
      queue: banner_queue
      routing-key: banner_routing_key