server:
  port: 8084

spring:
  application:
    name: blog-service
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    dynamic: true
    ssl:
      enabled: true
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5      # retry tối đa 5 lần
          initial-interval: 2000   # 2s
          multiplier: 2.0
          max-interval: 10000
        default-requeue-rejected: false
  cache:
    type: redis
    redis:
      time-to-live: 600000        # 10 phút (milliseconds)
      cache-null-values: false
      use-key-prefix: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      timeout: 2000ms
      password: ${REDIS_PASSWORD}

firebase:
  credentials:
    path: ${GOOGLE_APPLICATION_CREDENTIALS}

app:
  rabbitmq:
    exchange: main_exchange
    # Queue và routing key riêng cho từng service
    blog:
      queue: blog_queue
      routing-key: blog_routing_key
    banner:
      queue: banner_queue
      routing-key: banner_routing_key
