server:
  port: 8089

spring:
  application:
    name: payment-service
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    dynamic: true
    ssl:
      enabled: true
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5      # retry tối đa 5 lần
          initial-interval: 2000   # 2s
          multiplier: 2.0
          max-interval: 10000
        default-requeue-rejected: false

app:
  rabbitmq:
    exchange: main_exchange

    payment-request:
      queue: payment_request_queue
      routing-key: payment_request_routing_key

    order-status:
      routing-key: order_status_update_routing_key
    

payment:
  vnpay:
    url: ${VNP_URL:yourPaymentUrl}
    tmn-code: ${VNP_TMN_CODE:yourCode}
    secret-key: ${VNP_SECRET_KEY:yourKey}
    return-url: ${VNP_RETURN_URL:yourReturnUrl}
    ipn-url: ${VNP_IPN_URL:yourIpnUrl}
    version: ${VNP_VERSION:yourVersion}
    command: ${VNP_COMMAND:yourCommand}
    order-type: ${VNP_ORDER_TYPE:yourCommand}