server:
  port: 8089

spring:
  application:
    name: payment-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    stream:
      username: guest
      password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

app:
  rabbitmq:
    exchange: main_exchange
    # Queue và routing key riêng cho từng service
    order:
      queue: order_save_request_queue
      routing-key: order_save_request_routing_key
    payment-request:
      queue: payment_request_queue
      routing-key: payment_request_routing_key

    order-status:
      queue: order_status_update_queue
      routing-key: order_status_update_routing_key


payment:
  vnpay:
    url: ${VNP_URL:yourPaymentUrl}
    tmn-code: ${VNP_TMN_CODE:yourCode}
    secret-key: ${VNP_SECRET_KEY:yourKey}
    return-url: ${VNP_RETURN_URL:yourReturnUrl}
    version: ${VNP_VERSION:yourVersion}
    command: ${VNP_COMMAND:yourCommand}
    order-type: ${VNP_ORDER_TYPE:yourCommand}