server:
  port: 8091

spring:
  application:
    name: file-service
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    dynamic: true
    ssl:
      enabled: true
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5      # retry tối đa 5 lần
          initial-interval: 2000   # 2s
          multiplier: 2.0
          max-interval: 10000
        default-requeue-rejected: false

# path mặc định cho secrets; nếu muốn khác set env SUPABASE_SECRETS_PATH
app:
  rabbitmq:
    exchange: main_exchange
    file:
      queue: file_queue
      routing-key: file_routing_key
