server:
  port: 8085

spring:
  application:
    name: user-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    stream:
      username: ${RABBITMQ_USER}
      password: ${RABBITMQ_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

firebase:
  credentials:
    path: ${GOOGLE_APPLICATION_CREDENTIALS:../secrets/firebase-user.json}

app:
  rabbitmq:
    exchange: main_exchange
    # Queue và routing key riêng cho từng service
    user:
      queue: user_queue
      routing-key: user_routing_key