server:
  port: 8091

spring:
  application:
    name: file-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

# path mặc định cho secrets; nếu muốn khác set env SUPABASE_SECRETS_PATH
app:
  rabbitmq:
    exchange: main_exchange
    file:
      queue: file_queue
      routing-key: file_routing_key
