server:
  port: 8082

spring:
  application:
    name: order-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    stream:
      username: guest
      password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

firebase:
  credentials:
    path: ${GOOGLE_APPLICATION_CREDENTIALS:../secrets/firebase-order.json}

app:
  rabbitmq:
    exchange: main_exchange
    # Queue và routing key riêng cho từng service
    order:
      queue: order_queue
      routing-key: order_routing_key
    order-save-listener:
      queue: order_save_request_queue
      routing-key: order_save_request_routing_key

    order-checkout:
      queue: order_checkout_request_queue
      routing-key: order_checkout_request_routing_key

    stock-update-request:
      queue: stock_update_queue
      routing-key: stock_update_routing_key