server:
  port: 8082

spring:
  application:
    name: order-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    dynamic: true
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5      # retry tối đa 5 lần
          initial-interval: 2000   # 2s
          multiplier: 2.0
          max-interval: 10000
        default-requeue-rejected: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

firebase:
  credentials:
    path: ${GOOGLE_APPLICATION_CREDENTIALS:../secrets/firebase-order.json}

app:
  rabbitmq:
    exchange: main_exchange
    # Queue và routing key riêng cho từng service
    order:
      queue: order_queue
      routing-key: order_routing_key
    order-save-listener:
      queue: order_save_request_queue
      routing-key: order_save_request_routing_key

    order-checkout:
      queue: order_checkout_request_queue
      routing-key: order_checkout_request_routing_key

    order-status:
      queue: order_status_update_queue
      routing-key: order_status_update_routing_key

    stock-update-increase:
      routing-key: stock.update.increase

    stock-update-decrease:
      routing-key: stock.update.decrease

    stock-refund-request:
      queue: stock-refund-queue
      routing-key: stock-refund-routing-key

    order-mail:
      queue: order_mail_queue
      routing-key: order_mail_routing_key

