server:
  port: 8081

spring:
  application:
    name: product-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    dynamic: true
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5      # retry tối đa 5 lần
          initial-interval: 2000   # 2s
          multiplier: 2.0
          max-interval: 10000
        default-requeue-rejected: false
  elasticsearch:
    uris: http://elasticsearch:9200


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

firebase:
  credentials:
    path: ${GOOGLE_APPLICATION_CREDENTIALS:../secrets/firebase-product.json}


app:
  rabbitmq:
    exchange: main_exchange
    # Queue và routing key riêng cho từng service
    product:
      queue: product_queue
      routing-key: product_routing_key
    brand:
      queue: brand_queue
      routing-key: brand_routing_key
    category:
      queue: category_queue
      routing-key: category_routing_key
    stock-update-request:
      queue: stock_update_queue
      routing-key: stock_update_routing_key

logging:
  level:
    org.elasticsearch: warn