server:
  port: 8081

spring:
  application:
    name: product-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

firebase:
  credentials:
    path: ${GOOGLE_APPLICATION_CREDENTIALS:../secrets/firebase-product.json}

algolia:
  app-id: ${ALGOLIA_APP_ID}
  api-key: ${ALGOLIA_API_KEY}
  api-write-key: ${ALGOLIA_API_WRITE_KEY}
  index-name: products
