server:
  port: 8081

spring:
  application:
    name: product-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    stream:
      username: guest
      password: guest
  spring:
    elasticsearch:
      uris: http://elasticsearch:9200


eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

firebase:
  credentials:
    path: ${GOOGLE_APPLICATION_CREDENTIALS:../secrets/firebase-product.json}

algolia:
  app-id: ${ALGOLIA_APP_ID:yourAppId}
  api-key: ${ALGOLIA_API_KEY:yourAPIKey}
  api-write-key: ${ALGOLIA_API_WRITE_KEY:yourWriteKey}
  index-name: products

app:
  rabbitmq:
    exchange: main_exchange
    # Queue và routing key riêng cho từng service
    product:
      queue: product_queue
      routing-key: product_routing_key
    brand:
      queue: brand_queue
      routing-key: brand_routing_key
    category:
      queue: category_queue
      routing-key: category_routing_key
    stock-update-request:
      queue: stock_update_queue
      routing-key: stock_update_routing_key

logging:
  level:
    org.elasticsearch: warn