server:
  port: 8088

spring:
  application:
    name: inventory-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

firebase:
  credentials:
    path: ${GOOGLE_APPLICATION_CREDENTIALS:../secrets/firebase-inventory.json}

logging:
  level:
    root: INFO
    com.hmkeyewear.inventory_service: DEBUG
