server:
  port: 8083

spring:
  application:
    name: cart-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    stream:
      username: guest
      password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

firebase:
  credentials:
    path: ${GOOGLE_APPLICATION_CREDENTIALS:../secrets/firebase-cart.json}

app:
  rabbitmq:
    exchange: main_exchange
    cart:
      queue: cart_queue
      routing-key: cart_routing_key

    payment-request:
      queue: payment_request_queue
      routing-key: payment_request_routing_key

    order-checkout:
      queue: order_checkout_request_queue
      routing-key: order_checkout_request_routing_key

    order-save:
      queue: order_save_request_queue
      routing-key: order_save_request_routing_key

    discount:
      queue: discount_queue
      routing-key: discount_routing_key
