server:
  port: 8087

spring:
  application:
    name: store-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

firebase:
  credentials:
    path: ${GOOGLE_APPLICATION_CREDENTIALS:../secrets/firebase-store.json}

logging:
  level:
    root: INFO
    com.hmkeyewear.store_service: DEBUG
